---
- name: Validate SSM connectivity on Linux (and ensure Python)
  hosts: 10.135.130.117
  gather_facts: false
  collections:
    - amazon.aws
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_bucket_name: hf-jweier-dev
    ansible_aws_ssm_region: us-east-1
    ansible_remote_tmp: /tmp/.ansible/tmp

  pre_tasks:
    - name: Display Python version
      raw: "bash -c 'command -v python3 >/dev/null 2>&1 && python3 --version || (command -v python >/dev/null 2>&1 && python --version) || echo \"Python not found\"'"
      register: python_version_output

    - debug:
        var: python_version_output.stdout_lines

  #   - name: Prove SSM connectivity without Python (raw)
  #     ansible.builtin.raw: whoami
  #     register: who_raw
  #     changed_when: false

  #   - name: Show SSM execution user (raw)
  #     ansible.builtin.debug:
  #       msg: "SSM connected OK, raw whoami => {{ who_raw.stdout | default('') | trim }}"

  # tasks:
    # - name: Ensure remote temp dir exists
    #   raw: "mkdir -p /tmp/.ansible/tmp && chmod 700 /tmp/.ansible/tmp"

    